//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Material = new HashSet<Product_Material>();
        }
    
        public int idProduct { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public int MinCost { get; set; }
        public string Image { get; set; }
        public int CountOfWorkers { get; set; }
        public int idWorkshop { get; set; }
        public int idProductType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Material> Product_Material { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
